apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backend.fullname" . }}-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
