replicaCount: 1

image:
  repository: localhost:5000/aiops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8100

prometheus:
  host: prometheus-server
  port: 9090

resources:
  limits:
    cpu: 400m
    memory: 384Mi
  requests:
    cpu: 200m
    memory: 256Mi
