apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "load-generator.fullname" . }}
  labels:
    app: {{ include "load-generator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "load-generator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "load-generator.name" . }}
    spec:
      containers:
        - name: load-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8000"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
