replicaCount: 1

image:
  repository: localhost:5000/load-generator
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 150Mi
  limits:
    cpu: 400m
    memory: 256Mi
